### PR TITLE
Bug/numlock sync report spam

### LINKED ISSUE #18: Stuck in an infinite loop
Hi,

after flashing to the newest firmware version (from the stock firmware) I've noticed, that the num key no longer works.

After further investigation I found out, that after I activate Numpad layer, keyboard is constantly sending NumLock keycodes very rapidly.

Result of turning numpad on and off for fraction of second
----
Edit:
I've removed NumPad from the plugins list and NumLock key is no longer stuck. No led lightning, though. Tried to revert last couple commits but to no avail. IMHO this is integration issue.

### PR DESCRIPTION
**Pull request by obra**
This branch refactors the numpad plugin and updates the logic to be a bit more judicious about when to try to press the numlock key. It appears to resolve #18 

@algernon, I'd love your testing and review on this one. It's pretty late here and I'm not super confident this is a good and complete fix.

### CODE REVIEW

**Comment by algernon** [comment]
Haven't tested the code yet, but one thing I find curious is how the `NumLock` state sync is done. It's triggered from `afterEachCycle`, even though we want to do that when toggling the layer. For this purpose, I think `onKeyswitchEvent` is a better solution, because it doesn't run needlessly on every cycle.

I'll give this branch a try, and refactor it to use `onKeyswitchEvent` - if that still behaves as one would expect, I'll open a PR to update this one.

**Comment by algernon** [comment]
Gave my idea try too, and it's worse. Less lines, but more bytes compiled, and your version behaves better in some of the edge cases I've tried. For now, I think the changes are good, but I'll conduct some more testing during the day.

Will report back with my findings.

**Comment by algernon** [comment]
* Normal operation, when the Model01 is the only keyboard appears to work fine. I took the load on my host up to the skies (to make it report LED states slowly, if possible), still worked.
* Toggle NumLock on the Model01, then off on another keyboard, then off on the Model01: numlock stays off, as it should.
* Toggle NumLock on the Model01, then off on another keyboard, then back on, then off on the Model01:  numlock turns off, as it should.
* Toggle NumLock on on another keyboard, then on the Model01: numlock is on. Toggle it off on the Model01: turns off, as it should.

I think this should cover most bases.

File: src/Kaleidoscope-NumPad.h [hunk 1]
```diff
@@ -32,7 +32,14 @@ class NumPad_ : public kaleidoscope::Plugin {
...
-  static byte row, col;
+
+  void cleanupNumlockState(void);
+  void setKeyboardLEDColors(void);
+  bool getNumlockState(void);
+  void syncNumlockState(bool);
+
+  static uint8_t numpad_lock_key_row;
+  static uint8_t numpad_lock_key_col;
   static bool cleanupDone;
```
Comment (algernon) [inline src/Kaleidoscope-NumPad.h]: I'm not sure this is a good name anymore (`cleanupDone`, that is), but I don't have a better suggestion either.

**Review by algernon — APPROVED** [review]
Once the DCO bot is happy, I'm all for this.
